version: "3.5"

services:

  groimp:
    image: "debian:${DEBIAN_TAG}"
    build: 
      context: .
      args:
        DEBIAN_TAG: $DEBIAN_TAG
        JDK_PKG: $JDK_PKG
        JDK_HOME: $JDK_HOME
        GROIMP_PKG: $GROIMP_PKG
        GROIMP_VERSION: $GROIMP_VERSION
        GROIMP_DIR: $GROIMP_DIR
        JAVA_XMX: $JAVA_XMX
        DISPLAY: $DISPLAY	 
    volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
    command: java "-Xmx${JAVA_XMX}M" -jar "${GROIMP_DIR}/core.jar" --debug=INFO 
    network_mode: host
